### ISSUE TITLE
A Little Questions about Experiments in the Paper

### ISSUE THREAD

**Issue by zwandering** [matthias-wright/art-fid#10]
Thanks for your excellent paper and well-organized codes. I have few questions about the experiment settings in the paper though.

In section 4.1 of the paper, you said that "Style images are sampled from the WikiArt dataset [70] and the BAM dataset [78]." and "we compute the ArtFID with samples of 50k images." and "For each style transfer method, the ArtFID is computed with 5 different samples containing 50k images each.".

I have few questions about the experiment settings.

1. Are the style images sampled from the same style in WikiArt or do you use many styles seperately and calculate the mean ArtFID?
2. What is the meaning of "50k images"? 50k content images or 50k style images? If it refers to the number of content images, then how many style images do you use?
3. What is the meaning of "5 samples containing 50k images each"?

Thanks for your excellent paper again and I am hoping for your response!

**Comment by matthias-wright** [comment]
Hi @zwandering, thank you for reaching out!

1. The style images are uniformly randomly sampled from both the WikiArt and the BAM dataset.
2. 50k images here means 50k image pairs, so 50k style images and 50k content images. I could have made this clearer, sorry.
3. In order to calculate the ArtFID for one style transfer model, we randomly sampled 50k style images, then we randomly sampled 50k content images, and then computed the ArtFID with those images. We repeated this procedure 5 times for each model. Meaning, we had 5 samples, each containing 50k style images and 50k content images. And of course the samples were the same for each model.

Hope this helps!

**Comment by zwandering** [comment]
Do you mean you randomly sample 50k style images from both the WikiArt and the BAM dataset? Then, how do you ensure the style consistency of these 50k style images. I mean although these images are all from art images, they can still have very different styles. How do you tackle this problem?

**Comment by matthias-wright** [comment]
We wanted to test the models against a variety of style images, so this was intentional.

**Comment by zwandering** [comment]
Thanks, this solved my questions.
